import { GB, ES, FR, DE, IT, PT, RU, CN, JP, KR, NL, PL, SE, TR, SA, IN, TH, VN, GR, RO, HU, CZ, DK, FI, NO, HR, BG, SK, ID, NG, KE, IL, UA, IR, PH, PK } from 'country-flag-icons/react/3x2';

export const languages = [
  { code: 'GB', name: 'English', icon: GB, locale: 'en' },
  { code: 'CN', name: 'Chinese', icon: CN, locale: 'zh' },
  { code: 'JP', name: 'Japanese', icon: JP, locale: 'ja' },
  { code: 'KR', name: 'Korean', icon: KR, locale: 'ko' },
  { code: 'IN', name: 'Hindi', icon: IN, locale: 'hi' },
  { code: 'ID', name: 'Bahasa', icon: ID, locale: 'id' },
  { code: 'TH', name: 'Thai', icon: TH, locale: 'th' },
  { code: 'VN', name: 'Vietnamese', icon: VN, locale: 'vi' },
  { code: 'NG', name: 'Yoruba', icon: NG, locale: 'yo' },
  { code: 'KE', name: 'Swahili', icon: KE, locale: 'sw' },
  { code: 'ES', name: 'Spanish', icon: ES, locale: 'es' },
  { code: 'FR', name: 'French', icon: FR, locale: 'fr' },
  { code: 'DE', name: 'German', icon: DE, locale: 'de' },
  { code: 'IT', name: 'Italian', icon: IT, locale: 'it' },
  { code: 'PT', name: 'Portuguese', icon: PT, locale: 'pt' },
  { code: 'TR', name: 'Turkish', icon: TR, locale: 'tr' },
  { code: 'SA', name: 'Arabic', icon: SA, locale: 'ar' },
  { code: 'GR', name: 'Greek', icon: GR, locale: 'el' },
  { code: 'RU', name: 'Russian', icon: RU, locale: 'ru' },
  { code: 'NL', name: 'Dutch', icon: NL, locale: 'nl' },
  { code: 'PL', name: 'Polish', icon: PL, locale: 'pl' },
  { code: 'SE', name: 'Swedish', icon: SE, locale: 'sv' },
  { code: 'IL', name: 'Hebrew', icon: IL, locale: 'he' },
  { code: 'RO', name: 'Romanian', icon: RO, locale: 'ro' },
  { code: 'HU', name: 'Hungarian', icon: HU, locale: 'hu' },
  { code: 'CZ', name: 'Czech', icon: CZ, locale: 'cs' },
  { code: 'DK', name: 'Danish', icon: DK, locale: 'da' },
  { code: 'FI', name: 'Finnish', icon: FI, locale: 'fi' },
  { code: 'NO', name: 'Norwegian', icon: NO, locale: 'no' },
  { code: 'HR', name: 'Croatian', icon: HR, locale: 'hr' },
  { code: 'BG', name: 'Bulgarian', icon: BG, locale: 'bg' },
  { code: 'SK', name: 'Slovak', icon: SK, locale: 'sk' },
  { code: 'UA', name: 'Ukrainian', icon: UA, locale: 'uk' },
  { code: 'IR', name: 'Farsi', icon: IR, locale: 'fa' },
  { code: 'PH', name: 'Tagalog', icon: PH, locale: 'tl' },
  { code: 'PK', name: 'Urdu', icon: PK, locale: 'ur' }
];
