import { GB, ES, FR, DE, IT, PT, RU, CN, JP, KR, NL, PL, SE, TR, SA, IN, TH, VN, GR, RO, HU, CZ, DK, FI, NO, HR, BG, SK, ID, NG, KE, IL, UA, IR, PH, PK } from 'country-flag-icons/react/3x2';

export const languages = [
  { code: 'GB', name: 'English', icon: GB },
  { code: 'CN', name: 'Chinese', icon: CN },
  { code: 'JP', name: 'Japanese', icon: JP },
  { code: 'KR', name: 'Korean', icon: KR },
  { code: 'IN', name: 'Hindi', icon: IN },
  { code: 'ID', name: 'Bahasa', icon: ID },
  { code: 'TH', name: 'Thai', icon: TH },
  { code: 'VN', name: 'Vietnamese', icon: VN },
  { code: 'NG', name: 'Yoruba', icon: NG },
  { code: 'KE', name: 'Swahili', icon: KE },
  { code: 'ES', name: 'Spanish', icon: ES },
  { code: 'FR', name: 'French', icon: FR },
  { code: 'DE', name: 'German', icon: DE },
  { code: 'IT', name: 'Italian', icon: IT },
  { code: 'PT', name: 'Portuguese', icon: PT },
  { code: 'TR', name: 'Turkish', icon: TR },
  { code: 'SA', name: 'Arabic', icon: SA },
  { code: 'GR', name: 'Greek', icon: GR },
  { code: 'RU', name: 'Russian', icon: RU },
  { code: 'NL', name: 'Dutch', icon: NL },
  { code: 'PL', name: 'Polish', icon: PL },
  { code: 'SE', name: 'Swedish', icon: SE },
  { code: 'IL', name: 'Hebrew', icon: IL },
  { code: 'RO', name: 'Romanian', icon: RO },
  { code: 'HU', name: 'Hungarian', icon: HU },
  { code: 'CZ', name: 'Czech', icon: CZ },
  { code: 'DK', name: 'Danish', icon: DK },
  { code: 'FI', name: 'Finnish', icon: FI },
  { code: 'NO', name: 'Norwegian', icon: NO },
  { code: 'HR', name: 'Croatian', icon: HR },
  { code: 'BG', name: 'Bulgarian', icon: BG },
  { code: 'SK', name: 'Slovak', icon: SK },
  { code: 'UA', name: 'Ukrainian', icon: UA },
  { code: 'IR', name: 'Farsi', icon: IR },
  { code: 'PH', name: 'Tagalog', icon: PH },
  { code: 'PK', name: 'Urdu', icon: PK }
];
