import {
  US, CN, ES, IN, PT, BR, FR, DE, JP, AE, RU, KR, ID, IT, NL, TR, PL, SE,
  MY, RO, UA, GR, CZ, DK, FI, BG, HR, SK, HU, NO, VN, PH, ZA, AM, AZ, BY,
  BA, EE, GE, NG, IL, IS, IE, KZ, KG, LV, LT, LU, MK, NP, AF, IR, RS, SI,
  SO, KE, TH, PK, GB
} from 'country-flag-icons/react/3x2';

export const interface_locales = [
  { code: 'US', name: 'English', native_name: 'English', icon: US, locale: 'en' },
  { code: 'CN', name: 'Chinese', native_name: '中文', icon: CN, locale: 'zh' },
  { code: 'ES', name: 'Spanish', native_name: 'Español', icon: ES, locale: 'es' },
  { code: 'IN', name: 'Hindi', native_name: 'हिन्दी', icon: IN, locale: 'hi' },
  { code: 'PT', name: 'Portuguese (Portugal)', native_name: 'Português (Portugal)', icon: PT, locale: 'pt' },
  { code: 'BR', name: 'Portuguese (Brazil)', native_name: 'Português (Brasil)', icon: BR, locale: 'pt-br' },
  { code: 'FR', name: 'French', native_name: 'Français', icon: FR, locale: 'fr' },
  { code: 'DE', name: 'German', native_name: 'Deutsch', icon: DE, locale: 'de' },
  { code: 'JP', name: 'Japanese', native_name: '日本語', icon: JP, locale: 'ja' },
  { code: 'AE', name: 'Arabic', native_name: 'العربية', icon: AE, locale: 'ar' },
  { code: 'RU', name: 'Russian', native_name: 'Русский', icon: RU, locale: 'ru' },
  { code: 'KR', name: 'Korean', native_name: '한국어', icon: KR, locale: 'ko' },
  { code: 'ID', name: 'Indonesian', native_name: 'Bahasa Indonesia', icon: ID, locale: 'id' },
  { code: 'IT', name: 'Italian', native_name: 'Italiano', icon: IT, locale: 'it' },
  { code: 'NL', name: 'Dutch', native_name: 'Nederlands', icon: NL, locale: 'nl' },
  { code: 'TR', name: 'Turkish', native_name: 'Türkçe', icon: TR, locale: 'tr' },
  { code: 'PL', name: 'Polish', native_name: 'Polski', icon: PL, locale: 'pl' },
  { code: 'SE', name: 'Swedish', native_name: 'Svenska', icon: SE, locale: 'sv' },
  { code: 'MY', name: 'Malay', native_name: 'Bahasa Melayu', icon: MY, locale: 'ms' },
  { code: 'RO', name: 'Romanian', native_name: 'Română', icon: RO, locale: 'ro' },
  { code: 'UA', name: 'Ukrainian', native_name: 'Українська', icon: UA, locale: 'uk' },
  { code: 'GR', name: 'Greek', native_name: 'Ελληνικά', icon: GR, locale: 'el' },
  { code: 'CZ', name: 'Czech', native_name: 'Čeština', icon: CZ, locale: 'cs' },
  { code: 'DK', name: 'Danish', native_name: 'Dansk', icon: DK, locale: 'da' },
  { code: 'FI', name: 'Finnish', native_name: 'Suomi', icon: FI, locale: 'fi' },
  { code: 'BG', name: 'Bulgarian', native_name: 'Български', icon: BG, locale: 'bg' },
  { code: 'HR', name: 'Croatian', native_name: 'Hrvatski', icon: HR, locale: 'hr' },
  { code: 'SK', name: 'Slovak', native_name: 'Slovenčina', icon: SK, locale: 'sk' },
  { code: 'IN', name: 'Tamil', native_name: 'தமிழ்', icon: IN, locale: 'ta' },
  { code: 'HU', name: 'Hungarian', native_name: 'Magyar', icon: HU, locale: 'hu' },
  { code: 'NO', name: 'Norwegian', native_name: 'Norsk', icon: NO, locale: 'no' },
  { code: 'VN', name: 'Vietnamese', native_name: 'Tiếng Việt', icon: VN, locale: 'vi' },
  { code: 'PH', name: 'Filipino', native_name: 'Filipino', icon: PH, locale: 'tl' },
  { code: 'ZA', name: 'Afrikaans', native_name: 'Afrikaans', icon: ZA, locale: 'af' },
  { code: 'AM', name: 'Armenian', native_name: 'Հայdelays', icon: AM, locale: 'hy' },
  { code: 'IN', name: 'Assamese', native_name: 'অসমীয়া', icon: IN, locale: 'as' },
  { code: 'AZ', name: 'Azerbaijani', native_name: 'Azərbaycan', icon: AZ, locale: 'az' },
  { code: 'BY', name: 'Belarusian', native_name: 'Беларуская', icon: BY, locale: 'be' },
  { code: 'IN', name: 'Bengali', native_name: 'বাংলা', icon: IN, locale: 'bn' },
  { code: 'BA', name: 'Bosnian', native_name: 'Bosanski', icon: BA, locale: 'bs' },
  { code: 'ES', name: 'Catalan', native_name: 'Català', icon: ES, locale: 'ca' },
  { code: 'EE', name: 'Estonian', native_name: 'Eesti', icon: EE, locale: 'et' },
  { code: 'ES', name: 'Galician', native_name: 'Galego', icon: ES, locale: 'gl' },
  { code: 'GE', name: 'Georgian', native_name: 'ქართული', icon: GE, locale: 'ka' },
  { code: 'IN', name: 'Gujarati', native_name: 'ગુજરાતી', icon: IN, locale: 'gu' },
  { code: 'NG', name: 'Hausa', native_name: 'Hausa', icon: NG, locale: 'ha' },
  { code: 'IL', name: 'Hebrew', native_name: 'עברית', icon: IL, locale: 'he' },
  { code: 'IS', name: 'Icelandic', native_name: 'Íslenska', icon: IS, locale: 'is' },
  { code: 'IE', name: 'Irish', native_name: 'Gaeilge', icon: IE, locale: 'ga' },
  { code: 'ID', name: 'Javanese', native_name: 'Basa Jawa', icon: ID, locale: 'jv' },
  { code: 'IN', name: 'Kannada', native_name: 'ಕನ್ನಡ', icon: IN, locale: 'kn' },
  { code: 'KZ', name: 'Kazakh', native_name: 'Қazақша', icon: KZ, locale: 'kk' },
  { code: 'KG', name: 'Kyrgyz', native_name: 'Кыргызча', icon: KG, locale: 'ky' },
  { code: 'LV', name: 'Latvian', native_name: 'Latviešu', icon: LV, locale: 'lv' },
  { code: 'LT', name: 'Lithuanian', native_name: 'Lietuvių', icon: LT, locale: 'lt' },
  { code: 'LU', name: 'Luxembourgish', native_name: 'Lëtzebuergesch', icon: LU, locale: 'lb' },
  { code: 'MK', name: 'Macedonian', native_name: 'Македонски', icon: MK, locale: 'mk' },
  { code: 'IN', name: 'Malayalam', native_name: 'മലയാളം', icon: IN, locale: 'ml' },
  { code: 'IN', name: 'Marathi', native_name: 'मराठी', icon: IN, locale: 'mr' },
  { code: 'NP', name: 'Nepali', native_name: 'नेपाली', icon: NP, locale: 'ne' },
  { code: 'AF', name: 'Pashto', native_name: 'پښتو', icon: AF, locale: 'ps' },
  { code: 'IR', name: 'Persian', native_name: 'فارسی', icon: IR, locale: 'fa' },
  { code: 'IN', name: 'Punjabi', native_name: 'ਪੰਜਾਬੀ', icon: IN, locale: 'pa' },
  { code: 'RS', name: 'Serbian', native_name: 'Српски', icon: RS, locale: 'sr' },
  { code: 'IN', name: 'Sindhi', native_name: 'سنڌي', icon: IN, locale: 'sd' },
  { code: 'SI', name: 'Slovenian', native_name: 'Slovenščina', icon: SI, locale: 'sl' },
  { code: 'SO', name: 'Somali', native_name: 'Soomaali', icon: SO, locale: 'so' },
  { code: 'KE', name: 'Swahili', native_name: 'Kiswahili', icon: KE, locale: 'sw' },
  { code: 'IN', name: 'Telugu', native_name: 'తెలుగు', icon: IN, locale: 'te' },
  { code: 'TH', name: 'Thai', native_name: 'ไทย', icon: TH, locale: 'th' },
  { code: 'PK', name: 'Urdu', native_name: 'اردو', icon: PK, locale: 'ur' },
  { code: 'GB', name: 'Welsh', native_name: 'Cymraeg', icon: GB, locale: 'cy' },
];

export const learnable_languages = [
  { code: 'US', name: 'English', native_name: 'English', icon: US, iso639: 'eng' },
  { code: 'CN', name: 'Chinese', native_name: '中文', icon: CN, iso639: 'zho' },
  { code: 'ES', name: 'Spanish', native_name: 'Español', icon: ES, iso639: 'spa' },
  { code: 'IN', name: 'Hindi', native_name: 'हिन्दी', icon: IN, iso639: 'hin' },
  { code: 'PT', name: 'Portuguese (Portugal)', native_name: 'Português (Portugal)', icon: PT, iso639: 'por' },
  { code: 'BR', name: 'Portuguese (Brazil)', native_name: 'Português (Brasil)', icon: BR, iso639: 'por-br' },
  { code: 'FR', name: 'French', native_name: 'Français', icon: FR, iso639: 'fra' },
  { code: 'DE', name: 'German', native_name: 'Deutsch', icon: DE, iso639: 'deu' },
  { code: 'JP', name: 'Japanese', native_name: '日本語', icon: JP, iso639: 'jpn' },
  { code: 'AE', name: 'Arabic', native_name: 'العربية', icon: AE, iso639: 'ara' },
  { code: 'RU', name: 'Russian', native_name: 'Русский', icon: RU, iso639: 'rus' },
  { code: 'KR', name: 'Korean', native_name: '한국어', icon: KR, iso639: 'kor' },
  { code: 'ID', name: 'Indonesian', native_name: 'Bahasa Indonesia', icon: ID, iso639: 'ind' },
  { code: 'IT', name: 'Italian', native_name: 'Italiano', icon: IT, iso639: 'ita' },
  { code: 'NL', name: 'Dutch', native_name: 'Nederlands', icon: NL, iso639: 'nld' },
  { code: 'TR', name: 'Turkish', native_name: 'Türkçe', icon: TR, iso639: 'tur' },
  { code: 'PL', name: 'Polish', native_name: 'Polski', icon: PL, iso639: 'pol' },
  { code: 'SE', name: 'Swedish', native_name: 'Svenska', icon: SE, iso639: 'swe' },
  { code: 'MY', name: 'Malay', native_name: 'Bahasa Melayu', icon: MY, iso639: 'msa' },
  { code: 'RO', name: 'Romanian', native_name: 'Română', icon: RO, iso639: 'ron' },
  { code: 'UA', name: 'Ukrainian', native_name: 'Українська', icon: UA, iso639: 'ukr' },
  { code: 'GR', name: 'Greek', native_name: 'Ελληνικά', icon: GR, iso639: 'ell' },
  { code: 'CZ', name: 'Czech', native_name: 'Čeština', icon: CZ, iso639: 'ces' },
  { code: 'DK', name: 'Danish', native_name: 'Dansk', icon: DK, iso639: 'dan' },
  { code: 'FI', name: 'Finnish', native_name: 'Suomi', icon: FI, iso639: 'fin' },
  { code: 'BG', name: 'Bulgarian', native_name: 'Български', icon: BG, iso639: 'bul' },
  { code: 'HR', name: 'Croatian', native_name: 'Hrvatski', icon: HR, iso639: 'hrv' },
  { code: 'SK', name: 'Slovak', native_name: 'Slovenčina', icon: SK, iso639: 'slk' },
  { code: 'IN', name: 'Tamil', native_name: 'தமிழ்', icon: IN, iso639: 'tam' },
  { code: 'HU', name: 'Hungarian', native_name: 'Magyar', icon: HU, iso639: 'hun' },
  { code: 'NO', name: 'Norwegian', native_name: 'Norsk', icon: NO, iso639: 'nor' },
  { code: 'VN', name: 'Vietnamese', native_name: 'Tiếng Việt', icon: VN, iso639: 'vie' },
  { code: 'PH', name: 'Filipino', native_name: 'Filipino', icon: PH, iso639: 'fil' },
  { code: 'ZA', name: 'Afrikaans', native_name: 'Afrikaans', icon: ZA, iso639: 'afr' },
  { code: 'AM', name: 'Armenian', native_name: 'Հdelays', icon: AM, iso639: 'hye' },
  { code: 'IN', name: 'Assamese', native_name: 'অসমীয়া', icon: IN, iso639: 'asm' },
  { code: 'AZ', name: 'Azerbaijani', native_name: 'Azərbaycan', icon: AZ, iso639: 'aze' },
  { code: 'BY', name: 'Belarusian', native_name: 'Беларуская', icon: BY, iso639: 'bel' },
  { code: 'IN', name: 'Bengali', native_name: 'বাংলা', icon: IN, iso639: 'ben' },
  { code: 'BA', name: 'Bosnian', native_name: 'Bosanski', icon: BA, iso639: 'bos' },
  { code: 'ES', name: 'Catalan', native_name: 'Català', icon: ES, iso639: 'cat' },
  { code: 'EE', name: 'Estonian', native_name: 'Eesti', icon: EE, iso639: 'est' },
  { code: 'ES', name: 'Galician', native_name: 'Galego', icon: ES, iso639: 'glg' },
  { code: 'GE', name: 'Georgian', native_name: 'ქართული', icon: GE, iso639: 'kat' },
  { code: 'IN', name: 'Gujarati', native_name: 'ગુજરાતી', icon: IN, iso639: 'guj' },
  { code: 'NG', name: 'Hausa', native_name: 'Hausa', icon: NG, iso639: 'hau' },
  { code: 'IL', name: 'Hebrew', native_name: 'עברית', icon: IL, iso639: 'heb' },
  { code: 'IS', name: 'Icelandic', native_name: 'Íslenska', icon: IS, iso639: 'isl' },
  { code: 'IE', name: 'Irish', native_name: 'Gaeilge', icon: IE, iso639: 'gle' },
  { code: 'ID', name: 'Javanese', native_name: 'Basa Jawa', icon: ID, iso639: 'jav' },
  { code: 'IN', name: 'Kannada', native_name: 'ಕನ್ನಡ', icon: IN, iso639: 'kan' },
  { code: 'KZ', name: 'Kazakh', native_name: 'Қazақша', icon: KZ, iso639: 'kaz' },
  { code: 'KG', name: 'Kyrgyz', native_name: 'Кыргызча', icon: KG, iso639: 'kir' },
  { code: 'LV', name: 'Latvian', native_name: 'Latviešu', icon: LV, iso639: 'lav' },
  { code: 'LT', name: 'Lithuanian', native_name: 'Lietuvių', icon: LT, iso639: 'lit' },
  { code: 'LU', name: 'Luxembourgish', native_name: 'Lëtzebuergesch', icon: LU, iso639: 'ltz' },
  { code: 'MK', name: 'Macedonian', native_name: 'Македонски', icon: MK, iso639: 'mkd' },
  { code: 'IN', name: 'Malayalam', native_name: 'മലയാളം', icon: IN, iso639: 'mal' },
  { code: 'IN', name: 'Marathi', native_name: 'मराठी', icon: IN, iso639: 'mar' },
  { code: 'NP', name: 'Nepali', native_name: 'नेपाली', icon: NP, iso639: 'nep' },
  { code: 'AF', name: 'Pashto', native_name: 'پښتو', icon: AF, iso639: 'pus' },
  { code: 'IR', name: 'Persian', native_name: 'فارسی', icon: IR, iso639: 'fas' },
  { code: 'IN', name: 'Punjabi', native_name: 'ਪੰਜਾਬੀ', icon: IN, iso639: 'pan' },
  { code: 'RS', name: 'Serbian', native_name: 'Српски', icon: RS, iso639: 'srp' },
  { code: 'IN', name: 'Sindhi', native_name: 'سنڌي', icon: IN, iso639: 'snd' },
  { code: 'SI', name: 'Slovenian', native_name: 'Slovenščina', icon: SI, iso639: 'slv' },
  { code: 'SO', name: 'Somali', native_name: 'Soomaali', icon: SO, iso639: 'som' },
  { code: 'KE', name: 'Swahili', native_name: 'Kiswahili', icon: KE, iso639: 'swa' },
  { code: 'IN', name: 'Telugu', native_name: 'తెలుగు', icon: IN, iso639: 'tel' },
  { code: 'TH', name: 'Thai', native_name: 'ไทย', icon: TH, iso639: 'tha' },
  { code: 'PK', name: 'Urdu', native_name: 'اردو', icon: PK, iso639: 'urd' },
  { code: 'GB', name: 'Welsh', native_name: 'Cymraeg', icon: GB, iso639: 'cym' },
];
